plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
relative_links:
  enabled: true
  collections: true
include:
  - README.md

#theme: jekyll-theme-tactile
markdown: kramdown
theme: jekyll-theme-slate