# Site settings
title: Business Process Integration Lab
description: Materials about Linked Data


plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
relative_links:
  enabled: true
  collections: true
include:
  - README.md

markdown: kramdown
theme: jekyll-theme-midnight
